#!/bin/bash
start_date=$(date)
echo $start_date > /tmp/start_script.txt
set -e
cd /tmp/
file_http_time=$(curl -s -v -X HEAD https://xn--b1agjhrfhd.xn--b1ab2a0a.xn--b1aew.xn--p1ai/upload/expired-passports/list_of_expired_passports.csv.bz2 2>&1 | grep  -i '^< Last-Modified:'| cut -d" " -f 3-)
epoch_file_time=$(date -d "$file_http_time" +%s)

baza_file_time=$(PGPASSWORD=$POSTGRES_PASSWORD psql -qtAX -U $POSTGRES_USER -h $POSTGRES_HOST -d $POSTGRES_DB -c "SELECT date_d FROM public.app_date_download;")
if [[ -z $baza_file_time  ]]
then
  baza_file_time=0
  PGPASSWORD=$POSTGRES_PASSWORD psql --set=POSTGRES_USER="$POSTGRES_USER" -U $POSTGRES_USER  -h $POSTGRES_HOST -d $POSTGRES_DB -c "INSERT INTO public.app_date_download VALUES(1,0);"
fi
if [[ $epoch_file_time -gt $(PGPASSWORD=$POSTGRES_PASSWORD psql -qtAX -U $POSTGRES_USER -h $POSTGRES_HOST -d $POSTGRES_DB -c "SELECT date_d FROM public.app_date_download;") ]]
then
   wget https://xn--b1agjhrfhd.xn--b1ab2a0a.xn--b1aew.xn--p1ai/upload/expired-passports/list_of_expired_passports.csv.bz2
   bzip2 -d /tmp/list_of_expired_passports.csv.bz2
   PGPASSWORD=$POSTGRES_PASSWORD psql --set=POSTGRES_USER="$POSTGRES_USER" -U $POSTGRES_USER  -h $POSTGRES_HOST -d $POSTGRES_DB -c "DROP SEQUENCE IF EXISTS public.app_passports_id_seq CASCADE;"
   PGPASSWORD=$POSTGRES_PASSWORD psql --set=POSTGRES_USER="$POSTGRES_USER" -U $POSTGRES_USER  -h $POSTGRES_HOST -d $POSTGRES_DB -c "CREATE SEQUENCE public.app_passports_id_seq
     INCREMENT 1
     START 1
     MINVALUE 1
     MAXVALUE 2147483647
     CACHE 1;"
   PGPASSWORD=$POSTGRES_PASSWORD psql --set=POSTGRES_USER="$POSTGRES_USER" -U $POSTGRES_USER  -h $POSTGRES_HOST -d $POSTGRES_DB -c "ALTER SEQUENCE public.app_passports_id_seq OWNER TO $POSTGRES_USER;"
   PGPASSWORD=$POSTGRES_PASSWORD psql --set=POSTGRES_USER="$POSTGRES_USER" -U $POSTGRES_USER  -h $POSTGRES_HOST -d $POSTGRES_DB -f "/etc/periodic/hourly/create.sql"
   rm list_of_expired_passports.csv
   PGPASSWORD=$POSTGRES_PASSWORD psql --set=POSTGRES_USER="$POSTGRES_USER" -U $POSTGRES_USER  -h $POSTGRES_HOST -d $POSTGRES_DB -c "UPDATE public.app_date_download SET date_d=$epoch_file_time;"

fi
